server:
  port: 8888
  servlet:
    context-path: /act-track-api

spring:
  application:
    name: act-track
  datasource:
    username: act_track_user
    password: act_track_user
    url: jdbc:postgresql://localhost:5432/act_track_db
    driver-class-name: org.postgresql.Driver
    tomcat:
      abandon-when-percentage-full: 60
      max-active: 50
      max-idle: 10
      min-idle: 5
      validation-query=: 1
      test-while-idle: true
      validation-interval: 5000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#    hibernate:
#      ddl-auto: update
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: debug



# this needs to present to supply the data dir from which the json files would be processed or can supplied in cmd args
act-process-dir: /var/act-track
